// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX7NWjgBFiKJP2CGO5Wqk2X5oDiMGAIHA',
    appId: '1:399808752144:web:27ee9db7b1f781a1f5f895',
    messagingSenderId: '399808752144',
    projectId: 'blackjack101-app',
    authDomain: 'blackjack101-app.firebaseapp.com',
    storageBucket: 'blackjack101-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVXgx63gOUUwEq0rk28YQ2popMD_k68wU',
    appId: '1:399808752144:android:6abc45408682abf8f5f895',
    messagingSenderId: '399808752144',
    projectId: 'blackjack101-app',
    storageBucket: 'blackjack101-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJXS9yFZKa8Ku4Vk4VxmLnzRJL-C2Chj8',
    appId: '1:399808752144:ios:30fd0f3fc4fa18fcf5f895',
    messagingSenderId: '399808752144',
    projectId: 'blackjack101-app',
    storageBucket: 'blackjack101-app.firebasestorage.app',
    iosClientId: '399808752144-3nlfag8j2k98s1lhsgg5fijd6i59jge4.apps.googleusercontent.com',
    iosBundleId: 'com.blackjack101.blackjack101',
  );

}